### ISSUE TITLE
Support `extraVolumes` for Cribl workergroups helm charts

### ISSUE THREAD

**Issue by Kavinraja-G** [criblio/helm-charts#170]
I would like to enable `extraVolumes` support in helm values similar to what we have for `extraVolumeMounts`. Any reason for not enabling it ?

I have a use case where I need to add `extraVolumes` to enable WLI in GKE. Let me know if it's good to work, I ll enable them. Thanks!

**Comment by bdalpe** [comment]
@Kavinraja-G by defining `extraVolumeMounts` in your values, you will also add the volume definition to the pod.

See: https://github.com/criblio/helm-charts/blob/master/helm-chart-sources/logstream-workergroup/templates/_pod.tpl#L120-L131

If this doesn't fix the issue, please let me know.

**Comment by Kavinraja-G** [comment]
Nah, that doesn't help in my use-case. Check out [Sample App in Anthos using WLI example](https://cloud.google.com/anthos/clusters/docs/multi-cloud/aws/how-to/use-workload-identity-aws#deploy_a_sample_application) it has custom `volumes` & `volumeMounts` that I need to configure.

**Comment by bdalpe** [comment]
Looks like you need `extraSecretMounts`... This should accomplish your use case based on the linked document:

```
env:
  AWS_ROLE_ARN: goat
  AWS_WEB_IDENTITY_TOKEN_FILE: /var/run/secrets/aws-iam-token/serviceaccount/token
  AWS_REGION: us-west-2
extraSecretMounts:
  - name: aws-iam-token
    mountPath: /var/run/secrets/aws-iam-token/serviceaccount
    readOnly: true
    projected:
      defaultMode: 420
      sources:
        - serviceAccountToken:
            audience: sts.amazonaws.com
            expirationSeconds: 86400
            path: token
```

This outputs the correct `volumeMount` and `volume` settings on the Pod definition.
