### ISSUE TITLE
Support for OpenShift Routes

### ISSUE THREAD

**Issue by kenmoini** [criblio/helm-charts#184]
**Problem Statement:**
Many enterprise organizations rely on Red Hat OpenShift for their Kubernetes platform.  When deploying to OpenShift, it provides a type of Ingress called a Route.
It's not a traditional Ingress and instead uses a CustomResource called Routes.  It would look something like this:

```yaml
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: cribl
  namespace: cribl-stream
  labels:
    app.kubernetes.io/instance: ls-wg-pci
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: logstream-workergroup
    app.kubernetes.io/version: 4.4.3
    helm.sh/chart: logstream-workergroup-4.4.3
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: cribl-cribl-stream.apps.core-ocp.d70.lab.kemo.network # optional
  to:
    kind: Service
    name: ls-leader
    weight: 100
  port:
    targetPort: api
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None
```

This would be another optional template provided by the logstream-leader chart, similar to how Hashicorp provides the capability: https://github.com/hashicorp/vault-helm/blob/main/templates/server-route.yaml

**Solution Option(s):**
- Create an optional template that creates a Route object such as how Ingresses are created.
