### ISSUE TITLE
Hardcoded transport `tcp` comms to the leader node

### ISSUE THREAD

**Issue by michaelhyatt** [criblio/helm-charts#192]
The template seem to hardcode `tcp` as the protocol. Can you please add support for `tls`?

https://github.com/criblio/helm-charts/blob/c04136618a64067ecb42088c817872f5b9ea208f/helm-chart-sources/logstream-leader/templates/_pod.tpl#L89
https://github.com/criblio/helm-charts/blob/c04136618a64067ecb42088c817872f5b9ea208f/helm-chart-sources/logstream-leader/templates/_pod.tpl#L91

**Comment by yenoromm** [comment]
A string value at config.overrideLeaderURL would be ideal. This would provide a very flexible value for also configuring tls.<settingName> in the url

**Comment by bdalpe** [comment]
@michaelhyatt @yenoromm You can do this today.

1. Create a secret (either on your own or use the `extraObjects` value)
2. Configure your Helm Values like the following:
```
config: 
  useExistingSecret: true

envValueFrom:
  - name: CRIBL_DIST_MASTER_URL
    valueFrom:
      secretKeyRef:
        name: <secretName>
        key: <secretKey>
```

Bonus setting for extraObjects:

```
extraObjects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: cribl-leader-secret
    type: Opaque
    data:
      leaderUrl: "tls://authToken@criblleader:4200?group=foo"  
```

Extra objects supports a string or object for each array item. You can see more examples of how to use this in https://github.com/criblio/helm-charts/blob/master/helm-chart-sources/logstream-workergroup/tests/extras_test.yaml
