### ISSUE TITLE
logstream-leader chart services overly opinionated

### ISSUE THREAD

**Issue by PrymalInstynct** [criblio/helm-charts#213]
It is my belief that the helm chart default values and the way that those values are converted into manifests is far too opinionated.

1) The Ingress value forces the use of a NodePort service if you enable it, and it shuts off any configuration turning on the leadercomm port
2) if you want your externalType to be Loadbalancer for the Leadercomm port it prevents you from using an ingress on the API port.

See my solution below to "overwrite" the opinionated config to end up in a place that worked.

I would love to see the ingress and service manifest templates in the chart updated to support a wider range of options.

```
          service:
            internalType: ClusterIP
            externalType: LoadBalancer
            ports:
              - name: api
                port: 9000
                protocol: TCP
                external: false
              - name: leadercomm
                port: 4200
                protocol: TCP
                external: true
          extraObjects:
            - apiVersion: networking.k8s.io/v1
              kind: Ingress
              metadata:
                name: cribl-leader
              spec:
                ingressClassName: nginx
                rules:
                - host: cribl-leader.local.domain
                  http:
                    paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: cribl-leader-internal
                          port:
                            number: 9000

```
