### ISSUE TITLE
Request - Add Pod Disruption Budget to chart.

### ISSUE THREAD

**Issue by tasnyccbs** [criblio/helm-charts#228]
Is it possible to add `Pod Disruption Budget` to the chart to be able to enable if we want?

values.yaml can be something like this:
```
podDisruptionBudget:
  enabled: false # Should a PodDisruptionBudget be created by the chart or not.
  minAvailable: 1
  maxUnavailable: null
```
Obviously the maintainers would have to add the `templates/pod-disruption-budget.yaml` for this. ( or whatever you want to call it)

I am currently using the `logstream-workergroup` chart on GKE.

The google gke UI shows this as recommended and would like to have it clear cribl from the list.

From GCP-GKE UI : 
_Cluster $CLUSTERNAME  has a Deployment whose Pod selector does not match an existing Pod Disruption Budget. This makes your workload vulnerable to disruption, as all Pods in the Deployment can be taken down at once in a scenario like node upgrade._

Thank you 
Taso
